version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - echo Installing webpack3-express4-typescript2
      - npm install
      - npm run build
#  pre_build:
#     commands:
#      - echo pre_build NA
  build:
    commands:
       - echo Build started on `date`
       - npm run build
  post_build:
    commands:
       - echo Build completed on `date`
artifacts:
  files:
    - dist/bundle.js
    - package.json
  discard-paths: yes
  # - location
  #discard-paths: yes
  #base-directory: location